classdef roll_test_Cl < base_test_Cl
    %% ROLL_TEST_CL Roll Test Class
    %   stores all data necessary to run a roll test on the model (generic)
    
    %% number of points for input timeseries
    properties
        jounce_input_n_pt (1,1) int64 {mustBePositive} = 10;
    end
    
    %% jounce input timeseries
    properties (Dependent)
        L_jounce_input timeseries;
        R_jounce_input timeseries;
    end
    
    %% define jounce curves
    methods
        function out = get.L_jounce_input(obj)
            obj_class = class(obj);
            switch obj_class
            case 'F_roll_test_Cl'
                out = timeseries( ...
                    linspace( ...
                        -obj.F_ref.SY.travel, ...
                        obj.F_ref.SY.travel, ...
                        obj.jounce_input_n_pt)', ...
                    linspace(0, obj.t_end, obj.jounce_input_n_pt)');
            case 'R_roll_test_Cl'
                out = timeseries( ...
                    linspace( ...
                        -obj.R_ref.SY.travel, ...
                        obj.R_ref.SY.travel, ...
                        obj.jounce_input_n_pt)', ...
                    linspace(0, obj.t_end, obj.jounce_input_n_pt)');
            end
        end
        function out = get.R_jounce_input(obj)
            obj_class = class(obj);
            switch obj_class
            case 'F_roll_test_Cl'
                out = timeseries( ...
                    linspace( ...
                        obj.F_ref.SY.travel, ...
                        -obj.F_ref.SY.travel, ...
                        obj.jounce_input_n_pt)', ...
                    linspace(0, obj.t_end, obj.jounce_input_n_pt)');
            case 'R_roll_test_Cl'
                out = timeseries( ...
                    linspace( ...
                        -obj.R_ref.SY.travel, ...
                        obj.R_ref.SY.travel, ...
                        obj.jounce_input_n_pt)', ...
                    linspace(0, obj.t_end, obj.jounce_input_n_pt)');
            end
        end
    end
    
end