function R_MR_plot(SP)
    figure(...
        'Name', 'Rear MR', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    
    hold on;
    grid on;
    plot(SP.R.SY.jounce_array * 1000, SP.R.SY.MR_array);
    axis([-40, 40, 0.8, 1.2]);
    xlabel("wheel travel (mm)");
    ylabel("motion ratio");
    title(['SH length = ', num2str(SP.R.RA.SH_radius), ...
           ', ratio = ', num2str(SP.R.RA.PR_radius / SP.R.RA.SH_radius), ...
           ', angle = ', num2str(SP.R.RA.angle)]);
    hold off;
end