function F_MR_plot(SP)
    figure(...
        'Name', 'Front MR', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    
    hold on;
    grid on;
    plot(SP.F.SY.jounce_array * 1000, SP.F.SY.MR_array);
    axis([-40, 40, 0.8, 1.2]);
    xlabel("wheel travel (mm)");
    ylabel("motion ratio");
    title(['SH length = ', num2str(SP.F.RA.SH_radius), ...
           ', ratio = ', num2str(SP.F.RA.PR_radius / SP.F.RA.SH_radius), ...
           ', angle = ', num2str(SP.F.RA.angle)]);
    hold off;
end