function F_MR_comparison(SP, out)
    figure(...
        'Name', 'Front MR (Simplified vs Actual)', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    axis([-40, 40, 0.8, 1.2]);
    hold on;
    grid on;
    plot( ...
        out.FL.SY.jounce.Data * 1000, ...
        - gradient(out.FL.SH.length.Data, out.FL.SY.jounce.Data), ...
        'r');
    plot( ...
        out.FR.SY.jounce.Data * 1000, ...
        - gradient(out.FR.SH.length.Data, out.FR.SY.jounce.Data), ...
        'g');
    plot(SP.F.SY.jounce_array * 1000, SP.F.SY.MR_array);
    xlabel('jounce (mm)');
    ylabel('Motion Ratio');
    legend('Left', 'Right', 'Simplified');
    hold off;
end