function steer_roll_graphs(SP, out)
    
    %% extract camber, steer, and ackermann samples
    [rack_grid, roll_grid] = ...
        meshgrid( ...
            SP.SC.F.steer_roll_test.rack_samples, ...
            SP.SC.F.steer_roll_test.roll_samples);
    
    L_WP_orientation_samples = ...
        resample( ...
            out.FL.WP.orientation, ...
            SP.SC.F.steer_roll_test.t_samples);
    R_WP_orientation_samples = ...
        resample( ...
            out.FR.WP.orientation, ...
            SP.SC.F.steer_roll_test.t_samples);
    camber_samples = L_WP_orientation_samples.Data(:,5);
    L_steer_samples = - L_WP_orientation_samples.Data(:,4);
    R_steer_samples = R_WP_orientation_samples.Data(:,4);
    [ackermann_percent, steer_diff, ackermann_diff] = ...
        ackermann_function( ...
            SP.G.wheelbase, ...
            SP.F.SY.static_track * 0.0254, ...
            L_steer_samples, ...
            R_steer_samples);
    
    %% assemble grids
    rack_sweep_n_pt = SP.SC.F.steer_roll_test.rack_sweep_n_pt;
    roll_sweep_n_pt = SP.SC.F.steer_roll_test.roll_sweep_n_pt;
    camber_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    L_steer_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    R_steer_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    steer_diff_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    ackermann_percent_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    ackermann_diff_grid = zeros(rack_sweep_n_pt, roll_sweep_n_pt);
    for i = 1:roll_sweep_n_pt
        for j = 1:rack_sweep_n_pt
            camber_grid(i,j) = ...
                camber_samples( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
            L_steer_grid(i,j) = ...
                L_steer_samples( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
            R_steer_grid(i,j) = ...
                R_steer_samples( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
            steer_diff_grid(i,j) = ...
                steer_diff( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
            ackermann_percent_grid(i,j) = ...
                ackermann_percent( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
            ackermann_diff_grid(i,j) = ...
                ackermann_diff( ...
                    i + (j - 1) * roll_sweep_n_pt, ...
                    1);
        end
    end
    average_steer_grid = (L_steer_grid + R_steer_grid) / 2;
    [~, min_roll_index] = min(abs(SP.SC.F.steer_roll_test.roll_samples));
    roll_steer_grid = ...
        average_steer_grid - ...
        average_steer_grid(min_roll_index, :);
    
    %% make plots
    figure(...
        'Name', 'FL Camber', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    hold on;
    grid on;
    surf(1000 * rack_grid, roll_grid, camber_grid);
    xlabel('Rack Tavel (mm)');
    ylabel('Roll Angle (deg)');
    zlabel('Left Wheel Camber (deg)');
    colorbar;
    hold off;
    
    figure(...
        'Name', 'Roll Steer', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    hold on;
    grid on;
    surf(1000 * rack_grid, roll_grid, roll_steer_grid);
    xlabel('Rack Tavel (mm)');
    ylabel('Roll Angle (deg)');
    zlabel('\delta roll (deg)');
    colorbar;
    hold off;
    
    figure(...
        'Name', 'Steer Angle Difference', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    hold on;
    grid on;
    surf(1000 * rack_grid, roll_grid, steer_diff_grid);
    %surf(1000 * rack_grid, roll_grid, ackermann_diff_grid);
    xlabel('Rack Tavel (mm)');
    ylabel('Roll Angle (deg)');
    zlabel('\Delta \delta (deg)');
    colorbar;
    hold off;
    
    figure(...
        'Name', 'Ackermann Percent', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    hold on;
    grid on;
    surf(1000 * rack_grid, roll_grid, ackermann_percent_grid);
    xlabel('Rack Tavel (mm)');
    ylabel('Roll Angle (deg)');
    zlabel('Ackermann Percent');
    colorbar;
    hold off;
    
end