function R_MR_comparison(SP, out)
    figure(...
        'Name', 'Rear MR (Simplified vs Actual)', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    axis([-40, 40, 0.8, 1.2])
    hold on;
    grid on;
    plot( ...
        out.RL.SY.jounce.Data * 1000, ...
        - gradient(out.RL.SH.length.Data, out.RL.SY.jounce.Data), ...
        'r');
    plot( ...
        out.RR.SY.jounce.Data * 1000, ...
        - gradient(out.RR.SH.length.Data, out.RR.SY.jounce.Data), ...
        'g');
    plot(SP.R.SY.jounce_array * 1000, SP.R.SY.MR_array);
    xlabel('jounce (mm)');
    ylabel('Motion Ratio');
    legend('Left', 'Right', 'Simplified');
    hold off;
end