function R_roll_center_graphs(~, out)
    %% positions as a function of roll angle
    figure(...
        'Name', 'Front Roll and Instant Center Plots', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    
    subplot(1,2,1);
    hold on;
    title('Lateral Positions')
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.R.SY.roll_center.Data(:, 1));
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.RL.SY.instant_center.Data(:, 1), ...
        'r');
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.RR.SY.instant_center.Data(:, 1), ...
        'g');
    legend('Roll Center', 'Left Instant Center', 'Right Instant Center');
    grid on;
    xlabel('Roll Angle (deg)');
    ylabel('Y (mm)');
    hold off;
    
    subplot(1,2,2);
    hold on;
    title('Vertical Positions')
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.R.SY.roll_center.Data(:, 2));
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.RL.SY.instant_center.Data(:, 2), ...
        'r');
    plot(...
        out.R.SY.roll_angle.Data(:, 1), ...
        1e3 * out.RR.SY.instant_center.Data(:, 2), ...
        'g');
    legend('Roll Center', 'Left Instant Center', 'Right Instant Center');
    grid on;
    xlabel('Roll Angle (deg)');
    ylabel('Z (mm)');
    hold off;
    
    %% 2D paths
    figure(...
        'Name', 'Front Roll and Instant Center Paths', ...
        'NumberTitle', 'off', ...
        'Color', 'white', ...
        'WindowState', 'maximized');
    paths_axis_handle = axes;
    set(paths_axis_handle, 'XDir', 'reverse');
    hold on;
    title('Front Roll and Instant Center Paths');
    plot(...
        1e3 * out.R.SY.roll_center.Data(:, 1), ...
        1e3 * out.R.SY.roll_center.Data(:, 2));
    plot(...
        1e3 * out.RL.SY.instant_center.Data(:, 1), ...
        1e3 * out.RL.SY.instant_center.Data(:, 2), ...
        'r');
    plot(...
        1e3 * out.RR.SY.instant_center.Data(:, 1), ...
        1e3 * out.RR.SY.instant_center.Data(:, 2), ...
        'g');
    legend('Roll Center', 'Left Instant Center', 'Right Instant Center');
    axis equal;
    grid on;
    xlabel('Y (mm)');
    ylabel('Z (mm)');
    hold off;
    
end